service: streamlit-diabetes
#runtime: python37
runtime: custom
env: flex

#basic_scaling:
#    max_instances: 2
#    idle_timeout: 10m
#
#resources:
#    cpu: 1
#    memory_gb: 1
#    disk_size_gb: 10

#entrypoint: gunicorn --chdir /opt/streamlit_diabetes -b 0.0.0.0:8080 app:server
#entrypoint: streamlit run host_app.py